### ISSUE TITLE
1.5.0.M1 compilation problems for EncryptedJwt configuration

### ISSUE THREAD

**Issue by tamershahin** [alvarosanchez/grails-spring-security-rest#165]
Hi Alvaro!

Thanks for you latest release.. we were waiting for it! :)

I got a compilation problem though :( 

When using the following configuration:

grails.plugin.springsecurity.rest.token.storage.jwt.useEncryptedJwt = true
grails.plugin.springsecurity.rest.token.storage.jwt.privateKeyPath = '/data/jwt/private_key.der'
grails.plugin.springsecurity.rest.token.storage.jwt.publicKeyPath = '/data/jwt/public_key.der'

-the app starts smoothly:

08-02-2015 13:31:47,833 DEBUG jwt.FileRSAKeyProvider Loading public/private key from DER files
08-02-2015 13:32:07,334 INFO  web.DefaultSecurityFilterChain Creating filter chain: Ant [pattern='/api/**'], [grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter@4555fe3f, com.odobo.grails.plugin.springsecurity.rest.RestAuthenticationFilter@14e8e321, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@3f35b909, grails.plugin.springsecurity.web.filter.GrailsRememberMeAuthenticationFilter@43b275ac, com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter@297ccfe3, org.springframework.security.web.access.ExceptionTranslationFilter@7adec006, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@68b1d3a5]
|Server running. Browse to http://localhost:8081/nc-api
......
......

-my authProvider is working, but when the plugin calls generateToken() method i got this exception all the time:

08-02-2015 13:32:17,160 DEBUG jwt.AbstractJwtTokenGenerator Generated claim set: {"sub":"950ec5f1c18e4e5d9ebc1deadceaec43","exp":1423405937,"iat":1423402337,"roles":["ROLE_NO_ROLES"]}
08-02-2015 13:32:17,355 ERROR [/nc-api].[default] Servlet.service() for servlet [default] in context with path [/nc-api] threw exception [Filter execution threw an exception] with root cause
java.lang.SecurityException: class "org.bouncycastle.crypto.modes.AEADBlockCipher"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
	at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
	at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.nimbusds.jose.crypto.AESGCM.createAESGCMCipher(AESGCM.java:86)
	at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:119)
	at com.nimbusds.jose.crypto.RSAEncrypter.encrypt(RSAEncrypter.java:142)
	at com.nimbusds.jose.JWEObject.encrypt(JWEObject.java:376)
	at com.nimbusds.jose.JWEObject$encrypt.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.odobo.grails.plugin.springsecurity.rest.token.generation.jwt.EncryptedJwtTokenGenerator.generateToken(EncryptedJwtTokenGenerator.groovy:33)

(when configuring the app with useSignedJwt=true config everything works like a charm)

I tried to shuffle the buildConfig compile list but no success:

plugins {
		// plugins for the build system only
		build ':tomcat:7.0.55'
		runtime ':hibernate4:4.3.6.1'
		// plugins for the compile step
		compile name: 'rabbitmq-native', version: 'latest.release'
		compile ':cache-headers:1.1.7'
		compile ':pluginator:0.2.2'
		compile ':redis-flexible-cache:0.3.3'

		compile ":spring-security-rest:1.5.0.M1", {
			exclude 'cors'
		}
	}

Any Idea?

**Comment by robertoschwald** [comment]
Same problem here!

```
2015-02-09 11:30:57,651 [ajp-bio-8009-exec-1 ] DEBUG com.odobo.grails.plugin.springsecurity.rest.token.generation.jwt.AbstractJwtTokenGenerator  - Generated claim set: {"exp":1524481457,"sub":"test","roles":["ROLE_ADMIN","ROLE_USER"],"iat":1524477857}
2015-02-09 11:30:57,843 [ajp-bio-8009-exec-1 ] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/testapp].[default]  - Servlet.service() for servlet [default] in context with path [/testapp] threw exception [Filter execution threw an exception] with root cause
java.lang.SecurityException: class "org.bouncycastle.crypto.modes.AEADBlockCipher"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:952)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:666)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
	at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
	at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.nimbusds.jose.crypto.AESGCM.createAESGCMCipher(AESGCM.java:86)
```

Also tried with 
    -Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true

without success.

**Comment by alvarosanchez** [comment]
This one is easy. It's a conflict of Grails code dependencies: for the documentation, they indirectly through itext a bouncycastle JAR (facepalm). To fix it, add this line to your `BuildConfig.groovy`'s `dependencies {...}` block:

    build("com.lowagie:itext:2.1.7") { excludes "bouncycastle:bcprov-jdk14:138", "org.bouncycastle:bcprov-jdk14:1.38" }

I'll add this to the documentation.

**Comment by robertoschwald** [comment]
For which version of Grails is this? I performed a dependency report, and for Grails 2.4.4 it seems to be
```
+--- org.grails:grails-docs:2.4.4
|    \--- org.xhtmlrenderer:core-renderer:R8
|    \--- org.yaml:snakeyaml:1.8
|    \--- org.grails:grails-gdoc-engine:1.0.1
|    \--- org.jsoup:jsoup:1.7.3
|    \--- com.lowagie:itext:2.0.8
|         \--- bouncycastle:bcmail-jdk14:138
|         \--- bouncycastle:bcprov-jdk14:138
|    \--- commons-lang:commons-lang:2.6
```

**Comment by alvarosanchez** [comment]
2.4.4. See this testing app:

https://github.com/alvarosanchez/grails-spring-security-rest/tree/develop/test/apps/jwt

**Comment by alvarosanchez** [comment]
By the way, those dependencies you saw on the report are the conflicting ones and must be excluded.

**Comment by robertoschwald** [comment]
Perfect. It works. Only wondering why your 2.4.4 grails-docs dependency on itext has a different version than mine.

**Comment by alvarosanchez** [comment]
The packaged one is `2.0.8`, the same as you. I'm just pulling a newer one, but it's irrelevant.
