### ISSUE TITLE
Guava dependency collision with selenium

### ISSUE THREAD

**Issue by robertoschwald** [alvarosanchez/grails-spring-security-rest#166]
Quick note: dependency guava r03 defined in plugin collides with guava 15.0 defined in selenium-support.

This leads to error:
``` 
geb.driver.DriverCreationException: failed to create driver from callback
...
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Joiner$MapJoiner.appendTo(Ljava/lang/StringBuilder;Ljava/lang/Iterable;)Ljava/lang/StringBuilder;
	at com.google.common.net.MediaType.toString(MediaType.java:674)
	at org.openqa.selenium.remote.http.JsonHttpCommandCodec.encode(JsonHttpCommandCodec.java:198)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:107)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:96)

```

Workaround was to exclude guava-io from plugin.

Dependency tree:
```
+--- org.seleniumhq.selenium:selenium-support:2.43.0
|    \--- org.seleniumhq.selenium:selenium-remote-driver:2.43.0
|         \--- org.json:json:20080701
|         \--- org.seleniumhq.selenium:selenium-api:2.43.0
|         \--- com.google.guava:guava:15.0
```

**Comment by alvarosanchez** [comment]
Looking into this, there's not much I can do. Guava is used inside the plugin, I can't control what user applications are bringing into the classpath.

Therefore I'm closing this issue.
