### ISSUE TITLE
Grails 3 Timeline

### ISSUE THREAD

**Issue by mengelhart** [alvarosanchez/grails-spring-security-rest#233]
Just wanted to checkin to see if there are migration plans for Grails 3 support for this plugin now that there is Spring Security support for Grails 3.

I'm just starting a greenfield project so I can hold out for a while during development as integration with this plugin is fairly easy but if it's not going to be upgraded for a while I may need to come up with a shorter term solution.

thanks for the great plugin!

**Comment by BradBrown** [comment]
I'm curious about this as well.  If I thought my skillset was up to the task, I'd attempt the upgrade to 3.0 myself, but alas...

**Comment by PatrickHuetter** [comment]
I'm interested in this too.

**Comment by rkimaoui** [comment]
+1 
I'm interested too.

**Comment by alvarosanchez** [comment]
Hi guys, sorry for the delay. I can confirm that I will work on the upgrade soon.

Stay tuned :)

**Comment by gykpro** [comment]
Desperately need it.
And thanks for the great work!

**Comment by ararog** [comment]
Ok @alvarosanchez but as far as I know spring-security-core is already available for Grails 3, in fact this one was easy to add to project by calling gradle dependencies, it could be the case to be there without be compatible?

Right now I could add it to build.gradle with the following line:

compile "org.grails.plugins:spring-security-core:3.0.0.M1"

**Comment by alvarosanchez** [comment]
There is a first version Grails 3 compatible, but it's far from production ready. The plugin (spring-security-core:3.0.0.M1) mostly works, but the build is broken.

**Comment by alvarosanchez** [comment]
2.0.0.M1 published: http://alvarosanchez.github.io/grails-spring-security-rest/2.0.0.M1/

**Comment by alicehelen** [comment]
thank you for the plugin update. 

I am trying to use the grails rest plugin version 2.0.0.M1 with grails 3.x application. Added the grails rest plugin dependency in build.gradle
compile "org.grails.plugins:spring-security-rest:2.0.0.M1"

Getting UnsupportedClassVersionError when trying to run the grails application

Bean instantiation via factory method failed; 
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is java.lang.UnsupportedClassVersionError: RestOauthUrlMappings : Unsupported major.minor version 52.0      
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119) spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObjectAbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBeanAbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBeanAbstractBeanFactory.java:199) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:116) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refreshAbstractApplicationContext.java:462) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:687) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) ~[spring-boot-1.2.6.RELEASE.jar:1.2.6.RELEASE]
at grails.boot.GrailsApp.run(GrailsApp.groovy:52) [grails-core-3.0.8.jar:3.0.8]
at grails.boot.GrailsApp.run(GrailsApp.groovy:330) [grails-core-3.0.8.jar:3.0.8]
Exception in thread "main" at grails.boot.GrailsApp.run(GrailsApp.groovy:319) [grails-core-3.0.8.jar:3.0.8]

**Comment by alvarosanchez** [comment]
What Java version are you using?

**Comment by alicehelen** [comment]
I am using jdk 1.7

**Comment by alicehelen** [comment]
Hi Alvarosanchez,
Could you please help me to resolve the above posted error related to UnsupportedClassVersionError for RestOauthUrlMappings? I am using jdk 1.7

**Comment by alvarosanchez** [comment]
Could you please try with `2.0.0.BUILD-SNAPSHOT`?

Add this repo to your `build.gradle`'s `repositories { ...}` block:

    maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local" }

**Comment by alicehelen** [comment]
I tried with plugin spring-security-rest:2.0.0.BUILD-SNAPSHOT and used this repository 
maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local" }

It is working fine. I am not getting the UnsupportedClassVersion error. 

thank you

**Comment by alvarosanchez** [comment]
Ok, it will be fixed permanently in upcoming releases. Thanks!
