### ISSUE TITLE
IllegalStateException when multiple requests made at the same time

### ISSUE THREAD

**Issue by ChrisDavis8** [alvarosanchez/grails-spring-security-rest#307]
Hi I have recently tried using spring security rest 1.5.4 with grails 2.5.5 after upgrading from grails 2.4.4 and I am now encountering the following error when the server recieves several requests to the URL end points around the same time so couldf that indicate a multi-threading issue?

`2016-11-05 22:38:44,454 [][ERROR][http-bio-9050-exec-2][][][UrlMappingsFilter] Error when matching URL mapping [/call/clear]:Cannot set request attribute - request is not active anymore!
java.lang.IllegalStateException: Cannot set request attribute - request is not active anymore!
	at grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:118)
	at grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:84)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.java:59)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
`

kind regards
Chris

**Comment by ChrisDavis8** [comment]
After some more testing I have found I can actually repeat it with grails 2.4.5 and 1.5.1 version of the plugin which I was on originally, however it is only happening in when running in the dev runapp environment

**Comment by alvarosanchez** [comment]
The exception is thrown by [`UrlMappingsFilter`](https://github.com/grails/grails-core/blob/2.5.x/grails-web-url-mappings/src/main/groovy/org/codehaus/groovy/grails/web/mapping/filter/UrlMappingsFilter.java#L194), so better report an issue at https://github.com/grails/grails-core/issues
