### ISSUE TITLE
error with OAuth Google provider - Grails 3.2.2

### ISSUE THREAD

**Issue by xmlking** [alvarosanchez/grails-spring-security-rest#308]
I am getting following error when I hit `http://localhost:8080/oauth/authenticate/google` 
I am using your snapshot version of `grails-spring-security-rest`
thanks

```
grails {
    plugin {
        springsecurity {
            rest {
                oauth {
                    frontendCallbackUrl = { String tokenValue -> "http://localhost:4200/welcome#${tokenValue}" }

                    google {
                        client = org.pac4j.oauth.client.Google2Client
                         key = System.getenv('googleKey')
                         secret = System.getenv('googleSecret')
                        scope = org.pac4j.oauth.client.Google2Client.Google2Scope.EMAIL_AND_PROFILE
                        defaultRoles = ['ROLE_USER', 'ROLE_GOOGLE']
                    }
                }

                token {
                    validation {
                        enableAnonymousAccess = true
                    }

                    storage {
                        jwt {
                            secret = 'qrD6h8K6S9503Q06Y6Rfk21TErImPYqa'
                            expiration = 3600
                        }
                    }
                }
            }
        }
    }
}
```
```
DEBUG orangedollar.Application - Running with Spring Boot v1.4.1.RELEASE, Spring v4.3.3.RELEASE
INFO orangedollar.Application - The following profiles are active: development

Configuring Spring Security Core ...
... finished configuring Spring Security Core


Configuring Spring Security REST 2.0.0.BUILD-SNAPSHOT...
... finished configuring Spring Security REST

INFO orangedollar.Application - Started Application in 12.766 seconds (JVM running for 14.223)
Grails application running at http://localhost:8080 in environment: development
ERROR org.grails.web.errors.GrailsExceptionResolver - MissingMethodException occurred when processing request: [GET] /oauth/authenticate/google
No signature of method: org.pac4j.oauth.client.Google2Client.getRedirectAction() is applicable for argument types: (org.pac4j.core.context.J2EContext, java.lang.Boolean) values: [org.pac4j.core.context.J2EContext@b5fa50a, true]
Possible solutions: getRedirectAction(org.pac4j.core.context.WebContext). Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at grails.plugin.springsecurity.rest.RestLogoutFilter.doFilter(RestLogoutFilter.groovy:82)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingMethodException: No signature of method: org.pac4j.oauth.client.Google2Client.getRedirectAction() is applicable for argument types: (org.pac4j.core.context.J2EContext, java.lang.Boolean) values: [org.pac4j.core.context.J2EContext@b5fa50a, true]
Possible solutions: getRedirectAction(org.pac4j.core.context.WebContext)
        at grails.plugin.springsecurity.rest.RestOauthController.authenticate(RestOauthController.groovy:58)
        ... 17 common frames omitted
```

**Comment by alvarosanchez** [comment]
Fixed via https://github.com/alvarosanchez/grails-spring-security-rest/commit/c4646cf15e887f110a21c46220cd92f754a45a1e
