### ISSUE TITLE
/api/logout  sending a 403 error

### ISSUE THREAD

**Issue by harjitdotsingh** [alvarosanchez/grails-spring-security-rest#346]
Hi there,

I'm running on grails 3.2.6 and when I call /api/logout on the client. Its giving me a 403 error . Any reason why ?

**Comment by volnei** [comment]
Can you share you application.yml settings?

**Comment by alvarosanchez** [comment]
You're likely missing the token to logout.

http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_logout

**Comment by harjitdotsingh** [comment]
I'm re-opening this. Here is the log 




2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/assets/**'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/**/js/**'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/**/css/**'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/**/images/**'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/**/favicon.ico'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/api/createUser'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/api/createUserWithPostBack'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/api/listAffliates'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/api/createReferrer'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/api/getReferrer/**'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/api/**'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 1 of 7 in additional filter chain; firing Filter: 'SecurityRequestHolderFilter'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 2 of 7 in additional filter chain; firing Filter: 'MutableLogoutFilter'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/logout'; against '/logoff'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 3 of 7 in additional filter chain; firing Filter: 'RestAuthenticationFilter'
2018-07-14 21:35:28.445 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestAuthenticationFilter      : Actual URI is /api/logout; endpoint URL is /api/login
2018-07-14 21:35:28.446 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 4 of 7 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2018-07-14 21:35:28.446 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 5 of 7 in additional filter chain; firing Filter: 'RestTokenValidationFilter'
2018-07-14 21:35:28.446 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestTokenValidationFilter     : Token found: eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSldTdjA3RE1CREdMNldvSUFiK1NDQXh3RlEybEVvd2RvSlNFRklFRmFWTGtVQnU0Z2FEYXh2YmdYWkIzUmlSUUVnSVhvRTNZZUlCZUlUT3JKemJRZ29Md2xOeVwvdkw3dnJ2TFN3XC9HalliMVdCUEdqYTk0RWpQaEc2V1ppQTBORTgxc3gwOE0xUkcxZmNWT1gxakRDZ3lPbHdFdmdBeUxMTXdGWitTU0ZEZ1JjV0dcL2NVWkRXMnhyV0pNNkhoS2JtclRvbGRUblwvamM3bEpyK01FalIzbE1HY25XWUpXRW9FMkgzcENpM0ZkTTBxc05NV2d0a2VPNUs4eUhlVUdFWjRXWlVtcU9DTkRpTkFwZ2lpVDJWNk1xb3NUQTlDSnRZeGd0VmFvc0JUQ2hpREtiNzFVblZ1dWp1M3NVVTJNRUZYRU8yclR3OE9Mc1ZKXC9VZHh5OUp6ckZySm9YSjEwUkxScXpKbkRueXUwdDNiN2ZQM1ZvR0FHZXkrdmMzYVgxeEU3cXZ4eFwvTFwvVUY3b1lXRmtlaXByTmhXbUdZMkpSOXE2cHpmSHl2M0Q3MmJvekYwZG9ydFwvKzhqdnpHY1hLY2tXNHBvWXVYSWpoQjdsWFhQQ05cLzhHXC82MWhZNWZaUzNGS2Y1Und0TG8yeUlGWTd0Wkxmblh2QzFNSHV3SDVaUEt4dTZXZThOOXNjaEZWWjlNMFd5YXhnSUFBQT09Iiwic3ViIjoicGFpZHVzZXIiLCJyb2xlcyI6WyJST0xFX1BBSUQiXSwiZXhwIjoxNTMxNjM2MDk3LCJpYXQiOjE1MzE2MTgwOTd9.apsqK_WWM7yg0CNAQr3_0_yhYdbL7kyQ-xHF_SkgTaM
2018-07-14 21:35:28.446 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestTokenValidationFilter     : Trying to authenticate the token
2018-07-14 21:35:28.446 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestAuthenticationProvider    : Use JWT: true
2018-07-14 21:35:28.447 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestAuthenticationProvider    : Trying to validate token eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSldTdjA3RE1CREdMNldvSUFiK1NDQXh3RlEybEVvd2RvSlNFRklFRmFWTGtVQnU0Z2FEYXh2YmdYWkIzUmlSUUVnSVhvRTNZZUlCZUlUT3JKemJRZ29Md2xOeVwvdkw3dnJ2TFN3XC9HalliMVdCUEdqYTk0RWpQaEc2V1ppQTBORTgxc3gwOE0xUkcxZmNWT1gxakRDZ3lPbHdFdmdBeUxMTXdGWitTU0ZEZ1JjV0dcL2NVWkRXMnhyV0pNNkhoS2JtclRvbGRUblwvamM3bEpyK01FalIzbE1HY25XWUpXRW9FMkgzcENpM0ZkTTBxc05NV2d0a2VPNUs4eUhlVUdFWjRXWlVtcU9DTkRpTkFwZ2lpVDJWNk1xb3NUQTlDSnRZeGd0VmFvc0JUQ2hpREtiNzFVblZ1dWp1M3NVVTJNRUZYRU8yclR3OE9Mc1ZKXC9VZHh5OUp6ckZySm9YSjEwUkxScXpKbkRueXUwdDNiN2ZQM1ZvR0FHZXkrdmMzYVgxeEU3cXZ4eFwvTFwvVUY3b1lXRmtlaXByTmhXbUdZMkpSOXE2cHpmSHl2M0Q3MmJvekYwZG9ydFwvKzhqdnpHY1hLY2tXNHBvWXVYSWpoQjdsWFhQQ05cLzhHXC82MWhZNWZaUzNGS2Y1Und0TG8yeUlGWTd0Wkxmblh2QzFNSHV3SDVaUEt4dTZXZThOOXNjaEZWWjlNMFd5YXhnSUFBQT09Iiwic3ViIjoicGFpZHVzZXIiLCJyb2xlcyI6WyJST0xFX1BBSUQiXSwiZXhwIjoxNTMxNjM2MDk3LCJpYXQiOjE1MzE2MTgwOTd9.apsqK_WWM7yg0CNAQr3_0_yhYdbL7kyQ-xHF_SkgTaM
2018-07-14 21:35:28.449 DEBUG --- [nio-8080-exec-6] g.p.s.r.t.s.jwt.JwtTokenStorageService   : Successfully verified JWT
2018-07-14 21:35:28.449 DEBUG --- [nio-8080-exec-6] g.p.s.r.t.s.jwt.JwtTokenStorageService   : Trying to deserialize the principal object
2018-07-14 21:35:28.453 DEBUG --- [nio-8080-exec-6] g.p.s.r.t.s.jwt.JwtTokenStorageService   : UserDetails deserialized: grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID
2018-07-14 21:35:28.454 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestAuthenticationProvider    : Now is Sat Jul 14 21:35:28 EDT 2018 and token expires at Sun Jul 15 02:28:17 EDT 2018
2018-07-14 21:35:28.455 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestAuthenticationProvider    : Expiration: 17569
2018-07-14 21:35:28.455 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestAuthenticationProvider    : Authentication result: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSldTdjA3RE1CREdMNldvSUFiK1NDQXh3RlEybEVvd2RvSlNFRklFRmFWTGtVQnU0Z2FEYXh2YmdYWkIzUmlSUUVnSVhvRTNZZUlCZUlUT3JKemJRZ29Md2xOeVwvdkw3dnJ2TFN3XC9HalliMVdCUEdqYTk0RWpQaEc2V1ppQTBORTgxc3gwOE0xUkcxZmNWT1gxakRDZ3lPbHdFdmdBeUxMTXdGWitTU0ZEZ1JjV0dcL2NVWkRXMnhyV0pNNkhoS2JtclRvbGRUblwvamM3bEpyK01FalIzbE1HY25XWUpXRW9FMkgzcENpM0ZkTTBxc05NV2d0a2VPNUs4eUhlVUdFWjRXWlVtcU9DTkRpTkFwZ2lpVDJWNk1xb3NUQTlDSnRZeGd0VmFvc0JUQ2hpREtiNzFVblZ1dWp1M3NVVTJNRUZYRU8yclR3OE9Mc1ZKXC9VZHh5OUp6ckZySm9YSjEwUkxScXpKbkRueXUwdDNiN2ZQM1ZvR0FHZXkrdmMzYVgxeEU3cXZ4eFwvTFwvVUY3b1lXRmtlaXByTmhXbUdZMkpSOXE2cHpmSHl2M0Q3MmJvekYwZG9ydFwvKzhqdnpHY1hLY2tXNHBvWXVYSWpoQjdsWFhQQ05cLzhHXC82MWhZNWZaUzNGS2Y1Und0TG8yeUlGWTd0Wkxmblh2QzFNSHV3SDVaUEt4dTZXZThOOXNjaEZWWjlNMFd5YXhnSUFBQT09Iiwic3ViIjoicGFpZHVzZXIiLCJyb2xlcyI6WyJST0xFX1BBSUQiXSwiZXhwIjoxNTMxNjM2MDk3LCJpYXQiOjE1MzE2MTgwOTd9.apsqK_WWM7yg0CNAQr3_0_yhYdbL7kyQ-xHF_SkgTaM, expiration:17569, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID, super:grails.plugin.springsecurity.rest.token.AccessToken@72ba83a6: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_PAID)
2018-07-14 21:35:28.456 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestTokenValidationFilter     : Token authenticated. Storing the authentication result in the security context
2018-07-14 21:35:28.456 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestTokenValidationFilter     : Authentication result: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSldTdjA3RE1CREdMNldvSUFiK1NDQXh3RlEybEVvd2RvSlNFRklFRmFWTGtVQnU0Z2FEYXh2YmdYWkIzUmlSUUVnSVhvRTNZZUlCZUlUT3JKemJRZ29Md2xOeVwvdkw3dnJ2TFN3XC9HalliMVdCUEdqYTk0RWpQaEc2V1ppQTBORTgxc3gwOE0xUkcxZmNWT1gxakRDZ3lPbHdFdmdBeUxMTXdGWitTU0ZEZ1JjV0dcL2NVWkRXMnhyV0pNNkhoS2JtclRvbGRUblwvamM3bEpyK01FalIzbE1HY25XWUpXRW9FMkgzcENpM0ZkTTBxc05NV2d0a2VPNUs4eUhlVUdFWjRXWlVtcU9DTkRpTkFwZ2lpVDJWNk1xb3NUQTlDSnRZeGd0VmFvc0JUQ2hpREtiNzFVblZ1dWp1M3NVVTJNRUZYRU8yclR3OE9Mc1ZKXC9VZHh5OUp6ckZySm9YSjEwUkxScXpKbkRueXUwdDNiN2ZQM1ZvR0FHZXkrdmMzYVgxeEU3cXZ4eFwvTFwvVUY3b1lXRmtlaXByTmhXbUdZMkpSOXE2cHpmSHl2M0Q3MmJvekYwZG9ydFwvKzhqdnpHY1hLY2tXNHBvWXVYSWpoQjdsWFhQQ05cLzhHXC82MWhZNWZaUzNGS2Y1Und0TG8yeUlGWTd0Wkxmblh2QzFNSHV3SDVaUEt4dTZXZThOOXNjaEZWWjlNMFd5YXhnSUFBQT09Iiwic3ViIjoicGFpZHVzZXIiLCJyb2xlcyI6WyJST0xFX1BBSUQiXSwiZXhwIjoxNTMxNjM2MDk3LCJpYXQiOjE1MzE2MTgwOTd9.apsqK_WWM7yg0CNAQr3_0_yhYdbL7kyQ-xHF_SkgTaM, expiration:17569, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID, super:grails.plugin.springsecurity.rest.token.AccessToken@72ba83a6: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_PAID)
2018-07-14 21:35:28.457 DEBUG --- [nio-8080-exec-6] g.p.s.rest.RestTokenValidationFilter     : Continuing the filter chain
2018-07-14 21:35:28.457 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 6 of 7 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2018-07-14 21:35:28.457 DEBUG --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /api/logout at position 7 of 7 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2018-07-14 21:35:28.460 DEBUG --- [nio-8080-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /api/logout; Attributes: [_DENY_]
2018-07-14 21:35:28.461 DEBUG --- [nio-8080-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSldTdjA3RE1CREdMNldvSUFiK1NDQXh3RlEybEVvd2RvSlNFRklFRmFWTGtVQnU0Z2FEYXh2YmdYWkIzUmlSUUVnSVhvRTNZZUlCZUlUT3JKemJRZ29Md2xOeVwvdkw3dnJ2TFN3XC9HalliMVdCUEdqYTk0RWpQaEc2V1ppQTBORTgxc3gwOE0xUkcxZmNWT1gxakRDZ3lPbHdFdmdBeUxMTXdGWitTU0ZEZ1JjV0dcL2NVWkRXMnhyV0pNNkhoS2JtclRvbGRUblwvamM3bEpyK01FalIzbE1HY25XWUpXRW9FMkgzcENpM0ZkTTBxc05NV2d0a2VPNUs4eUhlVUdFWjRXWlVtcU9DTkRpTkFwZ2lpVDJWNk1xb3NUQTlDSnRZeGd0VmFvc0JUQ2hpREtiNzFVblZ1dWp1M3NVVTJNRUZYRU8yclR3OE9Mc1ZKXC9VZHh5OUp6ckZySm9YSjEwUkxScXpKbkRueXUwdDNiN2ZQM1ZvR0FHZXkrdmMzYVgxeEU3cXZ4eFwvTFwvVUY3b1lXRmtlaXByTmhXbUdZMkpSOXE2cHpmSHl2M0Q3MmJvekYwZG9ydFwvKzhqdnpHY1hLY2tXNHBvWXVYSWpoQjdsWFhQQ05cLzhHXC82MWhZNWZaUzNGS2Y1Und0TG8yeUlGWTd0Wkxmblh2QzFNSHV3SDVaUEt4dTZXZThOOXNjaEZWWjlNMFd5YXhnSUFBQT09Iiwic3ViIjoicGFpZHVzZXIiLCJyb2xlcyI6WyJST0xFX1BBSUQiXSwiZXhwIjoxNTMxNjM2MDk3LCJpYXQiOjE1MzE2MTgwOTd9.apsqK_WWM7yg0CNAQr3_0_yhYdbL7kyQ-xHF_SkgTaM, expiration:17569, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID, super:grails.plugin.springsecurity.rest.token.AccessToken@72ba83a6: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@36a50897: Username: paiduser; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_PAID; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_PAID)
2018-07-14 21:35:28.461 DEBUG --- [nio-8080-exec-6] o.s.s.a.h.RoleHierarchyImpl              : getReachableGrantedAuthorities() - From the roles [ROLE_PAID] one can reach [ROLE_PAID] in zero or more steps.
2018-07-14 21:35:28.480 DEBUG --- [nio-8080-exec-6] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is not anonymous); delegating to AccessDeniedHandler

org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.AbstractAccessDecisionManager.checkAllowIfAllAbstainDecisions(AbstractAccessDecisionManager.java:70)
        at grails.plugin.springsecurity.access.vote.AuthenticatedVetoableDecisionManager.decide(AuthenticatedVetoableDecisionManager.groovy:50)
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:124)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at javax.servlet.FilterChain$doFilter.call(Unknown Source)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:118)
        at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
        at grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at javax.servlet.FilterChain$doFilter.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at javax.servlet.FilterChain$doFilter.call(Unknown Source)
        at grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:143)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)




The token is being passed.

Here are my settings



```
grails.plugin.springsecurity.userLookup.userDomainClassName = 'com.loci.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'com.loci.UserRole'
grails.plugin.springsecurity.authority.className = 'com.loci.Role'
grails.plugin.springsecurity.rest.token.validation.useBearerToken = false
grails.plugin.springsecurity.rest.token.validation.headerName = 'X-Auth-Token'
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
        [pattern: '/', access: ['permitAll']],
        [pattern: '/error', access: ['permitAll']],
        [pattern: '/index', access: ['permitAll']],
        [pattern: '/index.gsp', access: ['permitAll']],
        [pattern: '/shutdown', access: ['permitAll']],
        [pattern: '/assets/**', access: ['permitAll']],
        [pattern: '/**/js/**', access: ['permitAll']],
        [pattern: '/**/css/**', access: ['permitAll']],
        [pattern: '/**/images/**', access: ['permitAll']],
        [pattern: '/**/favicon.ico', access: ['permitAll']]
]

grails.plugin.springsecurity.filterChain.chainMap = [
        [pattern: '/assets/**', filters: 'none'],
        [pattern: '/**/js/**', filters: 'none'],
        [pattern: '/**/css/**', filters: 'none'],
        [pattern: '/**/images/**', filters: 'none'],
        [pattern: '/**/favicon.ico', filters: 'none'],
        [pattern: '/api/createUser', filters: 'none'],
        [pattern: '/api/createUserWithPostBack', filters: 'none'],
        [pattern: '/api/listAffliates', filters: 'none'],
        [pattern: '/api/createReferrer', filters: 'none'],
        [pattern: '/api/getReferrer/**', filters: 'none'],
        [pattern: '/api/**', filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'],

]

grails.plugin.springsecurity.rest.login.active = true
grails.plugin.springsecurity.rest.login.endpointUrl = '/api/login'
grails.plugin.springsecurity.rest.logout.endpointUrl = '/api/logout'

grails.plugin.springsecurity.rest.token.storage.useGorm= true
grails.plugin.springsecurity.rest.token.storage.gorm.tokenDomainClassName ="com.loci.LociAuthToken"
grails.plugin.springsecurity.rest.token.storage.gorm.tokenValuePropertyName= tokenValue
grails.plugin.springsecurity.rest.token.storage.gorm.usernamePropertyName = username

```
