### ISSUE TITLE
Getting exception while using the @secured annotation on my controller method

### ISSUE THREAD

**Issue by jaikishore08** [alvarosanchez/grails-spring-security-rest#361]
```
java.lang.IllegalArgumentException: Failed to evaluate expression 'MANAGER_MINDSHARE'
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:30)
	at grails.plugin.springsecurity.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.groovy:57)
	at grails.plugin.springsecurity.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.groovy)
```

  ```groovy
    @Secured(['MANAGER_MINDSHARE'])
    def getAll(){
        def status
        def result = [:]
        try{
            result.message = customerService.getAll()
            status = HttpStatus.OK

        }catch(Exception e){
            result.message = "Internal server error"
            status = HttpStatus.INTERNAL_SERVER_ERROR
            log.error "failed at customer controller getAll method",e
        }
        result.status = status.toString()
        render status: status,
                contentType: "application/json",
                text: (result as JSON)
    }
```

When i am using `@secured['permitAll']`, it's working fine.

**Plugins** :
```
compile "org.grails.plugins:spring-security-rest:2.0.0.M2"
compile 'org.grails.plugins:spring-security-core:3.2.0.M1'
```

**application.groovy** :
```
grails.plugin.springsecurity.userLookup.userDomainClassName = 'com.xticket.auth.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'com.xticket.auth.UserRole'
grails.plugin.springsecurity.authority.className = 'com.xticket.auth.Role'
grails.plugin.springsecurity.rest.login.active=true
grails.plugin.springsecurity.rest.login.endpointUrl='/login'
grails.plugin.springsecurity.rest.login.failureStatusCode=401
grails.plugin.springsecurity.rest.login.useJsonCredentials = true
//grails.plugin.springsecurity.rest.token.storage.jwt.expiration = 3600
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
        [pattern: '/',               access: ['permitAll']],
        [pattern: '/error',          access: ['permitAll']],
        [pattern: '/index',          access: ['permitAll']],
        [pattern: '/index.gsp',      access: ['permitAll']],
        [pattern: '/shutdown',       access: ['permitAll']],
        [pattern: '/assets/**',      access: ['permitAll']],
        [pattern: '/**/js/**',       access: ['permitAll']],
        [pattern: '/**/css/**',      access: ['permitAll']],
        [pattern: '/**/images/**',   access: ['permitAll']],
        [pattern: '/**/favicon.ico', access: ['permitAll']]
]
grails.plugin.springsecurity.filterChain.chainMap = [
        [pattern: '/',      		 filters: 'none'],  // default home page
        [pattern: '/assets/**',      filters: 'none'],
        [pattern: '/**/js/**',       filters: 'none'],
        [pattern: '/**/css/**',      filters: 'none'],
        [pattern: '/**/images/**',   filters: 'none'],
        [pattern: '/**/favicon.ico', filters: 'none'],
        //Stateless chain
        [
                pattern: '/**',
                filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
        ]
]
```

**Comment by volnei** [comment]
@jaikishore08, according to the Spring Security docs, all roles must start with ROLE_ prefix by default.
